<?php
class Toni_Introduce_Block_Template extends Mage_Core_Block_Template   {

    public function __construct() {

    parent::__construct();

    $this->setTemplate('Toni/Introduce/template.phtml');

     echo "";

    }
    public function _beforeToHtml()
    {
        $title = new Mage_Core_Block_Text();
        $title->setText("Naslov");
        $this->setChild('title',$title);

        $mid = new Mage_Core_Block_Html_Calendar();
        $this->setChild('the_first',$mid);

        //return parent::_beforeToHtml(); // TODO: Change the autogenerated stub
    }
}