<?php
class Toni_Ticket_Model_Response extends Mage_Core_Model_Abstract
{
    protected $_eventPrefix = 'ticket_response';

    protected $_eventObject = 'response';


    protected function _construct() {
        $this->_init('ticket/response');
    }
    public function _getData($key)
    {
        return Mage::helper('core')->quoteEscape(isset($this->_data[$key]) ? $this->_data[$key] : null);
        //return parent::_getData($key); // TODO: Change the autogenerated stub
    }
    public function getTicketId() {
        return Mage::helper('core')->quoteEscape($this->_getData('response_id'));
    }
    public function getMessage() {
        return Mage::helper('core')->quoteEscape($this->_getData('response'));
    }
    public function getCreator() {
        return Mage::helper('core')->quoteEscape($this->_getData('creator'));
    }
    public function getCreatedAt() {
        //return $this->getData('entity_id');
    }
    public function getUpdatedAt() {
        //return $this->getData('entity_id');
    }
}